apiVersion: sagemaker.aws.amazon.com/v1
kind: TrainingJob
metadata:
  name: xgboost-mnist-debugger
spec:
    hyperParameters:
        - name: max_depth
          value: "5"
        - name: eta
          value: "0.2"
        - name: gamma
          value: "4"
        - name: min_child_weight
          value: "6"
        - name: silent
          value: "0"
        - name: objective
          value: multi:softmax
        - name: num_class
          value: "10"
        - name: num_round
          value: "10"
    algorithmSpecification:
        trainingImage: 433757028032.dkr.ecr.us-west-2.amazonaws.com/xgboost:1
        trainingInputMode: File
    roleArn: arn:aws:iam::106212541028:role/MarinBuildInfrastructure-SagemakerIntegrationTestR-KPWEFB6V6MGJ
    region: us-west-2
    outputDataConfig:
        s3OutputPath: s3://marin-development-pipeline-test-data-106212541028/xgboost/
    resourceConfig:
        instanceCount: 1
        instanceType: ml.m4.xlarge
        volumeSizeInGB: 5
    stoppingCondition:
        maxRuntimeInSeconds: 86400
    inputDataConfig:
        - channelName: train
          dataSource:
            s3DataSource:
                s3DataType: S3Prefix
                s3Uri: s3://marin-development-pipeline-test-data-106212541028/train/
                s3DataDistributionType: FullyReplicated
          contentType: text/csv
          compressionType: None
        - channelName: validation
          dataSource:
            s3DataSource:
                s3DataType: S3Prefix
                s3Uri: s3://marin-development-pipeline-test-data-106212541028/validation/
                s3DataDistributionType: FullyReplicated
          contentType: text/csv
          compressionType: None
    debugHookConfig:
      s3OutputPath: s3://marin-development-pipeline-test-data-106212541028/debug/
      collectionConfigurations:
        - collectionName: metrics
          collectionParameters:
            - name: save_interval
              value: "10"
    debugRuleConfigurations:
      - ruleConfigurationName: Amazon-LossNotDecreasing
        ruleEvaluatorImage: 895741380848.dkr.ecr.us-west-2.amazonaws.com/sagemaker-debugger-rules:latest
        ruleParameters:
          - name: rule_to_invoke
            value: VanishingGradient
          - name: threshold
            value: "20.0"
    tags:
      - key: tagKey
        value: tagValue
